server:
  port: 8003
spring:
  application:
    name: user-ribbon-load-balance-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localpeer1:8761/eureka, http://localpeer2:8762/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'