spring:
  application:
    name: micro-eureka-server
---
spring:
  profiles: eureka-server-peer-first
server:
  port: 8761
eureka:
  instance:
    hostname: localpeer1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localpeer2:8762/eureka
---
spring:
  profiles: eureka-server-peer-second
server:
  port: 8762
eureka:
  instance:
    hostname: localpeer2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localpeer1:8761/eureka
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'